let ElementalMat = (/** @type {Registry.Material} */ event) => {
	event.create('springaline')
        .gem()
		.dust()
        .color(0x6ca6e0).iconSet(GTMaterialIconSet.RUBY)
	event.create('terraline')
        .gem()
		.dust()
        .color(0x70d968).iconSet(GTMaterialIconSet.RUBY)
	event.create('pyroline')
        .gem()
		.dust()
        .color(0xeda44a).iconSet(GTMaterialIconSet.RUBY)
	event.create('aeraline')
        .gem()
		.dust()
        .color(0xd6d660).iconSet(GTMaterialIconSet.RUBY)
	
	event.create('drenched_iron')
        .ingot()
        .color(0x5592d2).iconSet(GTMaterialIconSet.METALLIC)
		.flags(GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_PLATE)
	event.create('earthen_iron')
        .ingot()
        .color(0x55d272).iconSet(GTMaterialIconSet.METALLIC)
		.flags(GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_PLATE)
	event.create('aerial_iron')
        .ingot()
        .color(0xd2d055).iconSet(GTMaterialIconSet.METALLIC)
		.flags(GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_PLATE)
	event.create('blazing_iron')
        .ingot()
        .color(0xff4141).iconSet(GTMaterialIconSet.METALLIC)
		.flags(GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_PLATE)
}