let MysticMetals = (/** @type {Registry.Material} */ event) => {
	event.create('mithril')
        .ingot()
		.liquid()
        .element('mithril')
		.color(0x759c92).secondaryColor(0x85a89f).iconSet(GTMaterialIconSet.METALLIC)
    event.create('mithril_alloy')
	    .ingot()
		.liquid()
        .components('1x mithril', '1x silver')
        .color(0xbbc9c6).secondaryColor(0xd0dbd9).iconSet(GTMaterialIconSet.METALLIC)
    
	event.create('enderium')
	    .ingot()
		.liquid()
        .components('1x ender_pearl', '1x platinum', '3x lead')
        .color(0x26665a).secondaryColor(0x51948d).iconSet(GTMaterialIconSet.METALLIC)
    event.create('refined_obsidian')
	    .ingot()
		.liquid()
        .components('1x obsidian', '1x diamond', '3x osmium')
        .color(0x4d1c5c).secondaryColor(0x61406b).iconSet(GTMaterialIconSet.METALLIC)
	event.create('enderium_alloy')
	    .ingot()
		.liquid()
		.blastTemp(3500, 'high', 1024, 640)
        .components('1x enderium', '3x refined_obsidian')
        .color(0x4bc4b6).secondaryColor(0x65dbce).iconSet(GTMaterialIconSet.METALLIC)
    event.create('stellar')
	    .ingot()
        .color(0xfeffc6).secondaryColor(0x7fd7e2)//.color(0xf5f5df).secondaryColor(0xf5f57d).iconSet(GTMaterialIconSet.METALLIC)
   /*event.create('ember')
		.liquid()
        .color(0xff6600).secondaryColor(0xfffed4)//.color(0xf5f5df).secondaryColor(0xf5f57d).iconSet(GTMaterialIconSet.METALLIC)
   event.create('ember_alloy')
	    .ingot()
		.liquid()
        .color(0xff6600).secondaryColor(0xfffed4)//.color(0xf5f5df).secondaryColor(0xf5f57d).iconSet(GTMaterialIconSet.METALLIC)
   event.create('dawnstone')
	    .ingot()
		.liquid()
        .color(0xc4930c).secondaryColor(0xf7cf60)//.color(0xf5f5df).secondaryColor(0xf5f57d).iconSet(GTMaterialIconSet.METALLIC)
   */
   event.create('divine_gemstone')
	    .gem()
        .color(0xf8ff7e).secondaryColor(0xf0ff00).iconSet(GTMaterialIconSet.DIAMOND)
   
   event.create('source_steel')
        .ingot()
		.liquid()
        .color(0xb045e5).iconSet(GTMaterialIconSet.SHINY)
		.flags(GTMaterialFlags.GENERATE_PLATE)
}