let ViralIncubationMat = (/** @type {Registry.Material} */ event) => {
	event.create('detergent')
        .dust()
		.color(0xf7ffff).secondaryColor(0xd2fafa)
	event.create('enriched_cognitium')
        .liquid()
		.color(0x97ff82)//.secondaryColor(0x30fc71)
	event.create('sterile_cognitium')
        .liquid()
		.color(0x30fc71)
	event.create('cognitive_uranium')
        .liquid()
		.color(0x97ff82).secondaryColor(0x30fc71)
		
	event.create('escherichia_cadaver')
        .liquid()
		.color(0x9c6d16)
	event.create('escherichia_koli')
        .liquid()
		.color(0xa0f1f2)
	event.create('corynebacterium_sludge_marsenis')
        .liquid()
		.color(0x156309)
	event.create('pseudomonas_fluorescens')
        .liquid()
		.color(0xf598f3)
}