const Removal = (event) => {
	event.remove({ type: 'tfc:alloy' })
	event.remove({ mod: 'ironchest' })
	event.remove({ mod: 'ironfurnaces' })
	event.remove({ mod: 'createaddition' })
	//event.remove({ output: 'create:shaft' })
	event.remove({ output: 'vintageimprovements:vibrating_table' })
	//event.remove({ output: 'create:cogwheel' })
	//event.remove({ output: 'create:large_cogwheel' })
	event.remove({ type: 'vintageimprovements:hammering' })
	event.remove({ type: 'vintageimprovements:rolling' })
	event.remove({ type: 'createaddition:rolling' })
	event.remove({ type: 'vintageimprovements:coiling' })
	event.remove({ type: 'vintageimprovements:turning' })
	event.remove({ type: 'vintageimprovements:curving' })
	//event.remove({ type: 'vintageimprovements:pressurizing' })
	//event.remove({ type: 'vintageimprovements:vacumizing' })
	event.remove({ type: 'greate:compacting' })
	event.remove({ type: 'greate:pressing/integration' })
	event.remove({ type: 'create:pressing' })
	event.remove({ input: '#forge:tools/hammers', output: '#forge:plates'})
	event.remove({ input: '#forge:tools/hammers', output: '#forge:double_plates'})
	event.remove({ type: 'greate:pressing' })
	event.remove({ output: 'elementalcraft:buddingshrine' })
	event.remove({ output: 'elementalcraft:shrine_upgrade_springaline' })
	event.remove({ output: 'ae2:printed_silicon' })
	event.remove({ output: 'ae2:printed_calculation_processor' })
	event.remove({ output: 'ae2:printed_engineering_processor' })
	event.remove({ output: 'ae2:printed_logic_processor' })
	event.remove({ output: 'hostilenetworks:blank_data_model' })
	event.remove({ output: 'ae2:terminal' })
	event.remove({ output: 'ae2:formation_core' })
	event.remove({ output: 'ae2:annihilation_core' })
	event.remove({ output: 'ae2:cell_component_1k' })
	event.remove({ output: 'ae2:cell_component_4k' })
	event.remove({ output: 'ae2:controller' })
	event.remove({ output: 'embers:caminite_blend' })
	event.remove({ output: 'gtceu:compressed_clay' })
	event.remove({ output: 'gtceu:sticky_resin' })
	event.remove({ output: 'ae2:quartz_glass' })
	event.remove({ output: 'ae2:charged_certus_quartz_crystal' })
	event.remove({ output: 'ae2:quartz_fiber' })
	event.remove({ output: 'ae2:fluix_glass_cable' })
	event.remove({ output: 'ae2:fluix_covered_cable' })
	event.remove({ output: 'gtceu:wood_plate' })
	
	event.remove({ type: 'gtceu:centrifuge', input: 'minecraft:dirt' })
	event.remove({ type: 'gtceu:centrifuge', input: 'minecraft:grass_block' })
	event.remove({ type: 'gtceu:centrifuge', input: 'gtceu:sticky_resin' })
	event.remove({ output: 'create:sand_paper' })
	event.remove({ output: 'create:red_sand_paper' })
	//event.remove({ output: 'tfc:sandpaper' })
	event.remove({ output: 'createaddition:diamond_grit_sandpaper' })
	event.remove({ output: 'vintageimprovements:grinder_belt' })
	event.remove({ output: 'ae2:energy_acceptor' })
	//event.remove({ mod: 'ars_nouveau' })
	event.remove({ output: 'ad_astra:rocket_fin'})
	event.remove({ output: 'ad_astra:tier_1_rocket'})
	event.remove({ output: 'ad_astra:tier_2_rocket'})
	event.remove({ output: 'ad_astra:steel_engine'})
	event.remove({ output: 'ad_astra:engine_frame'})
	event.remove({ output: 'ad_astra:nasa_workbench'})
	event.remove({ input: 'ad_astra:nasa_workbench'})
	event.remove({ type: 'ad_astra:nasa_workbench'})
	event.remove({ mod: 'ad_astra', output: 'ad_astra:rocket_nose_cone' })
	event.remove({ mod: 'ad_astra', output: 'ad_astra:steel_tank' })
	event.remove({ output: 'ad_astra:desh_tank' })
	event.remove({ output: 'ad_astra:ostrum_tank' })
	event.remove({ output: 'ad_astra:calorite_tank' })
	event.remove({ mod: 'ad_astra', output: 'ad_astra:desh_engine' })
	event.remove({ mod: 'ad_astra', output: 'ad_astra:ostrum_engine' })
	event.remove({ mod: 'ad_astra', output: 'ad_astra:calorite_engine' })
	event.remove({ output: 'minecraft:bread' })
	event.remove({ output: 'minecraft:cookie' })
	event.remove({ output: 'minecraft:cake' })
	event.remove({ output: 'ad_astra:fan'})
	event.remove({ id: 'gtceu:chemical_reactor/titanium_tetrachloride' })
	event.remove({ id: 'gtceu:large_chemical_reactor/titanium_tetrachloride' })
	event.remove({ type: 'gtceu:centrifuge', input: '#forge:dusts/stone' })
	//event.remove({ type: 'gtceu:centrifuge', input: 'gtceu:sticky_resin' })
	event.remove({ type: 'enchanted:wheel' })
	event.remove({ output: 'enchanted:gypsum' })
	event.remove({ output: 'create:wheat_flour' })
	event.remove({ input: 'minecraft:wheat' })
	event.remove({ input: 'gtceu:wheat_dust' })
	event.remove({ output: 'tconstruct:pattern'})
}