let BlockRegistry = (/** @type {Registry.Item} */ event) => {
    event.create('tempered_borosilicate_glass')
		.defaultCutout()
		.textureAll("gtceu:block/casings/transparent/tempered_glass")
		.color(0xe8fffa)
		.renderType("translucent")
		.hardness(3.0)
		//.noItem()
	event.create('cleanroom_borosilicate_glass')
		.defaultCutout()
		.textureAll("gtceu:block/casings/transparent/cleanroom_glass")
		.color(0xe8fffa)
		.renderType("translucent")
		.hardness(2.0)
		
	event.create('springaline_glass')
		.defaultCutout()
		.textureAll("kubejs:block/springaline_glass")
		.color(0x6ca6e0)
		.renderType("translucent")
		.hardness(1.0)	
		
	event.create('terraline_glass')
		.defaultCutout()
		.textureAll("kubejs:block/terraline_glass")
		.color(0x70d968)
		.renderType("translucent")
		.hardness(1.0)	
		
	event.create('pyroline_glass')
		.defaultCutout()
		.textureAll("kubejs:block/pyroline_glass")
		.color(0xeda44a)
		.renderType("translucent")
		.hardness(1.0)	
		
	event.create('aeraline_glass')
		.defaultCutout()
		.renderType("translucent")
		.hardness(1.0)
		.textureAll("kubejs:block/aeraline_glass")	
		.color(0xd6d660)
	
	event.create('sky_stone_case')
		.defaultCutout()
		.textureAll("kubejs:block/sky_stone_case")
		.hardness(3.0)
	event.create('fluix_engraved_sky_stone_case')
		.defaultCutout()
		.textureAll("kubejs:block/fluix_engraved_sky_stone_case")
		.hardness(3.0)
}
