let ItemRegistry = (/** @type {Registry.Item} */ event) => {
    event.create('treated_lumber')
	event.create('ember_ingot')
	event.create('rainbow_ingot')
	event.create('hot_rainbow_ingot')
			.texture('layer0','kubejs:item/rainbow_ingot')
			.texture('layer1','gtceu:item/material_sets/metallic/ingot_hot_overlay')
	
	event.create('iron_of_the_elements_ingot')
	
	event.create('elemental_silk')
	event.create('water_silk')
	event.create('fire_silk')
	event.create('earth_silk')
	
	event.create('combined_will_crystal')
	
	event.create('polymer_clay')
	event.create('pulsating_mesh')
	event.create('pulsating_dust')
	event.create('petrotheum_dust')
	event.create('energized_clathrate')
	event.create('pyrotheum_dust')
	
	event.create('redstone_nanothread')
		.texture('layer0','kubejs:item/nanothread')
		.texture('layer1','kubejs:item/nanothread_secondary')
		.texture('layer2','kubejs:item/nanothread_overlay')
		.color(0, 0xff0000)
		.color(1, 0xff0000)
	
	event.create('fire_gem_dust')
		.texture('layer0','gtceu:item/material_sets/metallic/dust')
		.color(0, 0xff0000)
	event.create('earth_gem_dust')
		.texture('layer0','gtceu:item/material_sets/metallic/dust')
		.color(0, 0x00e04b)
	event.create('air_gem_dust')
		.texture('layer0','gtceu:item/material_sets/metallic/dust')
		.color(0, 0xffea00)
	event.create('water_gem_dust')
		.texture('layer0','gtceu:item/material_sets/metallic/dust')
		.color(0, 0x007be0)
	event.create('titanium_sponge')
	event.create('calculation_engineering_processor')
	event.create('logic_engineering_processor')
	event.create('engineering_logic_processor')
	event.create('calculation_logic_processor')
	event.create('logic_calculation_processor')
	event.create('engineering_calculation_processor')
	event.create('redstone_printed_silicon_wafer')
	
	event.create('water_micro_processor')
		.displayName("Water Processor")
	event.create('air_micro_processor')
		.displayName("Air Processor")
	event.create('earth_micro_processor')
		.displayName("Earth Processor")
	event.create('fire_micro_processor')
		.displayName("Fire Processor")
	event.create('elemental_micro_processor')
		.displayName("Elemental Processor")
	event.create('water_processor')
		.displayName("Water Processor Chip")
	event.create('air_processor')
		.displayName("Air Processor Chip")
	event.create('earth_processor')
		.displayName("Earth Processor Chip")
	event.create('fire_processor')
		.displayName("Fire Processor Chip")
	event.create('elemental_processor')
		.displayName("Elemental Processor Chip")
		
	event.create('water_capacitor')
	event.create('fire_capacitor')
	event.create('air_capacitor')
	event.create('earth_capacitor')
	event.create('elemental_capacitor')
	
	event.create('pulsating_printed_board')
	event.create('chaotic_pulsating_printed_board')
	event.create('air_processor_assembly')
	event.create('fire_processor_assembly')
	event.create('water_processor_assembly')
	event.create('earth_processor_assembly')
	
	event.create('processor_formation')
	event.create('logic_processor_formation')
	event.create('calculation_processor_formation')
	event.create('engineering_processor_formation')
	event.create('processing_formation_assembly')
	
	event.create('gold_thread')
	event.create('blood_stained_thread')
	event.create('fanciful_thread')
	
	event.create('void_quartz')
	event.create('dark_quartz')
	event.create('black_quartz')
	
	event.create('water_inductor')
	event.create('air_inductor')
	event.create('earth_inductor')
	event.create('fire_inductor')
	event.create('elemental_inductor')
	event.create('mithril_europium_alloy_23_inductor')
		.displayName("Mithril Europium Alloy-23 Inductor")
	event.create('mithril_europium_alloy_23_micro_processor')
		.displayName("Mithril Europium Alloy-23 Microprocessor")
	event.create('radioactive_inductor')
	event.create('radioactive_micro_processor')
		.displayName("Radioactive Microprocessor")
	
	//event.create('seasoned_mdf_composite')
	event.create('pressed_mdf_composite')
	event.create('formed_mdf_composite')
	
	event.create('sky_stone_plate')
	
	event.create('earth_silk_cloth')
		.texture('layer0','tfc:item/silk_cloth')
		.color(0, 0x55d272)
	event.create('fire_silk_cloth')
		.texture('layer0','tfc:item/silk_cloth')
		.color(0, 0xd27055)
	event.create('air_silk_cloth')
		.texture('layer0','tfc:item/silk_cloth')
		.color(0, 0xd2d055)
	event.create('water_silk_cloth')
		.texture('layer0','tfc:item/silk_cloth')
		.color(0, 0x5592d2)
		
	event.create('psychophage')
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0xff0303)
		
	event.create('chronophage')
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0x0209d1)
		
	event.create('lexophage')
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0xfcf003)
		
	event.create('radiophage')
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0x32a852)
	
	event.create('lambda_phage')
		.tooltip("Coliphage Escherichia virus Lambda")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0xffdd75)
	
	event.create('t4_phage')
		.tooltip("Escherichia virus T4")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0xb89837)
	
	event.create('t3_phage')
		.tooltip("Escherichia virus T3")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0x5baeb5)
		
	event.create('t7_phage')
		.tooltip("Escherichia virus T7")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0xb693c7)
	
	
	event.create('t1_ent_phage')
		.displayName("T1 Phage")
		.tooltip("Enterobacteria phage T1")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0x8a50a6)
		
	event.create('t2_ent_phage')
		.tooltip("Enterobacteria phage T2")
		.displayName("T2 Phage")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0xd9d97c)
		
	event.create('t3_ent_phage')
		.tooltip("Enterobacteria phage T3")
		.displayName("T3 Phage")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0x85b55b)
	
	event.create('m13_phage')
		.tooltip("Escherichia virus M13")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0xd97cc0)
	
	event.create('phi_phage')
		.tooltip("Escherichia virus Phi 174")
		.displayName("Phi 174 Phage")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0xd9bf7c)
	
	event.create('t1_phage')
		.tooltip("Escherichia virus T1")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0xbd705e)
	
	event.create('t2_phage')
		.tooltip("Escherichia virus T2")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0xb75ebd)
	
	event.create('ms2_phage')
		.tooltip("Emesvirus Zinderi")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0x8a5dcf)
	
	event.create('p_phi_6_phage')
		.tooltip("Pseudomonas virus Phi 6")
		.displayName("Phi 6 Phage")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0xf2304a)
	
	event.create('p_phi_7_phage')
		.tooltip("Pseudomonas virus Phi 7")
		.displayName("Phi 7 Phage")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0xede43e)
	
	event.create('p_phi_8_phage')
		.tooltip("Pseudomonas virus Phi 8")
		.displayName("Phi 8 Phage")
		.texture('layer0','kubejs:item/phage_anim')
		.color(0, 0x31ebb9)
		
	event.create('sterilized_petri_dish').texture('gtceu:item/petri_dish')
	/*event.create('cultured_petri_dish')
		.texture('layer0','kubejs:item/petri_culture')
		.texture('layer1','gtceu:item/petri_dish')
		.color(0, 0xf4ff55)*/
	
	event.create('cultured_petri_dish_rotten_flesh')
		.texture('layer0','kubejs:item/petri_culture')
		.texture('layer1','gtceu:item/petri_dish')
		.color(0, 0x9c6d16)
		.tooltip('Escherichia Cadaver (rotten flesh bacteria)')//.tooltip('A Petri Dish that contains Escherichia Cadaver (rotten flesh bacteria)')
		.displayName('Cultured Petri Dish')
	
	event.create('cultured_petri_dish_ecoli')
		.texture('layer0','kubejs:item/petri_culture')
		.texture('layer1','gtceu:item/petri_dish')
		.color(0, 0xa0f1f2)
		.tooltip('Escherichia Koli (E.Coli)')
		.displayName('Cultured Petri Dish')
	
	event.create('cultured_petri_dish_marsenis')
		.texture('layer0','kubejs:item/petri_culture')
		.texture('layer1','gtceu:item/petri_dish')
		.color(0, 0x156309)
		.tooltip('Corynebacterium Sludge Marsenis')
		.displayName('Cultured Petri Dish')
	
	event.create('cultured_petri_dish_fluorescens')
		.texture('layer0','kubejs:item/petri_culture')
		.texture('layer1','gtceu:item/petri_dish')
		.color(0, 0xf598f3)
		.tooltip('Pseudomonas Fluorescens')
		.displayName('Cultured Petri Dish')
}