const Kroll = (event) => {
	event.recipes.gtceu.large_chemical_reactor('kroll_t_tetrachloride')
		.itemInputs('2x gtceu:carbon_dust', 'gtceu:rutile_dust')
		.outputFluids('gtceu:carbon_monoxide 2000', 'gtceu:crude_titanium_tetrachloride 1000', 'gtceu:chloride_waste_i 1000')
		.duration(400)
		.EUt(480)
	event.recipes.gtceu.distillation_tower('distill_t_tetrachloride')
		.inputFluids('gtceu:crude_titanium_tetrachloride 1000')
		//.itemInputs('2x gtceu:carbon_dust', 'gtceu:rutile_dust')
		.outputFluids('gtceu:titanium_tetrachloride 1000', 'gtceu:chloride_waste_ii 1000')
		.duration(400)
		.EUt(480)
	event.recipes.gtceu.electrolyzer('elect_chloride_waste_1')
		.inputFluids('gtceu:chloride_waste_i 1000')
		//.itemInputs('2x gtceu:carbon_dust', 'gtceu:rutile_dust')
		.outputFluids('gtceu:iron_ii_chloride 500', 'gtceu:aluminium_chloride 300', 'gtceu:manganese_chloride 200')
		.duration(400)
		.EUt(480)
	event.recipes.gtceu.electrolyzer('elect_chloride_waste_2')
		.inputFluids('gtceu:chloride_waste_ii 1000')
		//.itemInputs('2x gtceu:carbon_dust', 'gtceu:rutile_dust')
		.outputFluids('gtceu:silicon_chloride 450', 'gtceu:tin_chloride 450', 'gtceu:vanadium_oxytrichloride 100')
		.duration(400)
		.EUt(480)
}