const stones = ["granite", "diorite", "gabbro", "shale", "claystone", "limestone", "conglomerate", "dolomite", "chert", "chalk", "rhyolite", "basalt", "andesite", "dacite", "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"]
const StoneRecipe = (event) => {
	event.recipes.gtceu.mixer('mix_silt')
		.itemInputs('createaddition:biomass', '2x #forge:dusts/stone')
		.itemOutputs('2x gtceu:silt_dust')
		.duration(400)
		.EUt(8)
	
	event.recipes.gtceu.mixer('mix_loam')
		.itemInputs('#forge:dusts/stone', '2x createaddition:biomass')
		.itemOutputs('2x gtceu:loam_dust')
		.duration(400)
		.EUt(8)
	
	event.recipes.gtceu.extractor('ext_biomass')
		.itemInputs('createaddition:biomass')
		.outputFluids('gtceu:biomass 1000')
		.duration(500)
		.EUt(8)
	
	event.recipes.gtceu.mixer('mix_bomass')
		.itemInputs('gtceu:bio_chaff', 'biomancy:organic_matter')
		.itemOutputs('2x createaddition:biomass')
		.duration(400)
		.EUt(8)
		
	event.recipes.gtceu.macerator('mac_flux_stone')
		.itemInputs('#tfc:fluxstone')
		.itemOutputs('2x tfc:powder/flux')
		.chancedOutput('tfc:powder/flux', 3000, 1)
		.duration(400)
		.EUt(8)
	
	stones.forEach((stone) => {
		event.recipes.gtceu.macerator(`macerate_${stone}_cobble`)
		.itemInputs(`tfc:rock/cobble/${stone}`)
		.itemOutputs(`tfc:rock/gravel/${stone}`)
		.chancedOutput(`tfc:rock/loose/${stone}`, 9000, 2)
		.chancedOutput(`tfc:rock/loose/${stone}`, 6000, 2)
		.chancedOutput(`tfc:rock/loose/${stone}`, 3000, 1)
		.duration(400)
		.EUt(8)
		event.recipes.gtceu.macerator(`macerate_${stone}_gravel`)
		.itemInputs(`tfc:rock/gravel/${stone}`)
		.itemOutputs(`gtceu:${stone}_dust`)
		.chancedOutput('minecraft:flint', 6000, 1)
		.duration(400)
		.EUt(8)
		event.recipes.gtceu.forge_hammer(`hammer_${stone}_hardened`)
		.itemInputs(`tfc:rock/hardened/${stone}`)
		.itemOutputs(`tfc:rock/raw/${stone}`)
		.duration(400)
		.EUt(8)
		event.recipes.gtceu.forge_hammer(`hammer_${stone}_raw`)
		.itemInputs(`tfc:rock/raw/${stone}`)
		.itemOutputs(`tfc:rock/cobble/${stone}`)
		.duration(400)
		.EUt(8)
		event.recipes.gtceu.forge_hammer(`hammer_${stone}_cobble`)
		.itemInputs(`tfc:rock/cobble/${stone}`)
		.itemOutputs(`tfc:rock/gravel/${stone}`)
		.duration(400)
		.EUt(8)
	})
}