const craftingMatTags = (event) => {
	event.add('kubejs:any_elemental_capacitor', 'kubejs:elemental_capacitor')
	event.add('kubejs:any_elemental_capacitor', 'kubejs:air_capacitor')
	event.add('kubejs:any_elemental_capacitor', 'kubejs:earth_capacitor')
	event.add('kubejs:any_elemental_capacitor', 'kubejs:fire_capacitor')
	event.add('kubejs:any_elemental_capacitor', 'kubejs:water_capacitor')
	
	event.add('kubejs:any_elemental_inductor', 'kubejs:elemental_inductor')
	event.add('kubejs:any_elemental_inductor', 'kubejs:air_inductor')
	event.add('kubejs:any_elemental_inductor', 'kubejs:earth_inductor')
	event.add('kubejs:any_elemental_inductor', 'kubejs:fire_inductor')
	event.add('kubejs:any_elemental_inductor', 'kubejs:water_inductor')
	
	event.add('kubejs:any_elemental_lv_circuit', 'kubejs:elemental_processor')
	event.add('kubejs:any_elemental_lv_circuit', 'kubejs:air_processor')
	event.add('kubejs:any_elemental_lv_circuit', 'kubejs:earth_processor')
	event.add('kubejs:any_elemental_lv_circuit', 'kubejs:fire_processor')
	event.add('kubejs:any_elemental_lv_circuit', 'kubejs:water_processor')
	
	event.add('kubejs:any_elemental_mv_circuit', 'kubejs:elemental_micro_processor')
	event.add('kubejs:any_elemental_mv_circuit', 'kubejs:air_micro_processor')
	event.add('kubejs:any_elemental_mv_circuit', 'kubejs:earth_micro_processor')
	event.add('kubejs:any_elemental_mv_circuit', 'kubejs:fire_micro_processor')
	event.add('kubejs:any_elemental_mv_circuit', 'kubejs:water_micro_processor')
	
	//event.add('kubejs:any_elemental_hv_circuit', 'kubejs:elemental_processor_assembly')
	event.add('kubejs:any_elemental_hv_circuit', 'kubejs:air_processor_assembly')
	event.add('kubejs:any_elemental_hv_circuit', 'kubejs:earth_processor_assembly')
	event.add('kubejs:any_elemental_hv_circuit', 'kubejs:fire_processor_assembly')
	event.add('kubejs:any_elemental_hv_circuit', 'kubejs:water_processor_assembly')
	
	
	event.add('forge:sand_dust', 'gtceu:brown_sand_dust')
  event.add('forge:sand_dust', 'gtceu:green_sand_dust')
  event.add('forge:sand_dust', 'gtceu:pink_sand_dust')
  event.add('forge:sand_dust', 'gtceu:red_sand_dust')
  event.add('forge:sand_dust', 'gtceu:white_sand_dust')
  event.add('forge:sand_dust', 'gtceu:black_sand_dust')
  event.add('forge:sand_dust', 'gtceu:yellow_sand_dust')
  event.add('forge:igneous_dust', 'gtceu:granite_dust')
  event.add('forge:igneous_dust', 'gtceu:diorite_dust')
  event.add('forge:igneous_dust', 'gtceu:gabbro_dust')
  event.add('forge:igneous_dust', 'gtceu:rhyolite_dust')
  event.add('forge:igneous_dust', 'gtceu:basalt_dust')
  event.add('forge:igneous_dust', 'gtceu:andesite_dust')
  event.add('forge:igneous_dust', 'gtceu:dacite_dust')
  
  event.add('forge:sedimentary_dust', 'gtceu:shale_dust')
  event.add('forge:sedimentary_dust', 'gtceu:claystone_dust')
  event.add('forge:sedimentary_dust', 'gtceu:limestone_dust')
  event.add('forge:sedimentary_dust', 'gtceu:conglomerate_dust')
  event.add('forge:sedimentary_dust', 'gtceu:dolomite_dust')
  event.add('forge:sedimentary_dust', 'gtceu:chert_dust')
  event.add('forge:sedimentary_dust', 'gtceu:chalk_dust')
  
  event.add('forge:metamorphic_dust', 'gtceu:quartzite_dust')
  event.add('forge:metamorphic_dust', 'gtceu:slate_dust')
  event.add('forge:metamorphic_dust', 'gtceu:phyllite_dust')
  event.add('forge:metamorphic_dust', 'gtceu:schist_dust')
  event.add('forge:metamorphic_dust', 'gtceu:gneiss_dust')
  event.add('forge:metamorphic_dust', 'gtceu:marble_dust')
  
  event.add('forge:dusts/stone', '#forge:igneous_dust')
  event.add('forge:dusts/stone', '#forge:sedimentary_dust')
  event.add('forge:dusts/stone', '#forge:metamorphic_dust')
  
  event.add('forge:latex_log', 'tfc:wood/log/kapok')
  event.add('forge:latex_log', 'tfc:wood/wood/kapok')
  event.add('forge:latex_log', 'afc:wood/log/hevea')
  event.add('forge:latex_log', 'afc:wood/wood/hevea')
  event.add('forge:latex_log', 'afc:wood/log/rubber_fig')
  event.add('forge:latex_log', 'afc:wood/wood/rubber_fig')
  
  event.add('forge:sap_log', 'tfc:wood/log/aspen')
  event.add('forge:sap_log', 'tfc:wood/wood/aspen')
  event.add('forge:sap_log', 'tfc:wood/log/ash')
  event.add('forge:sap_log', 'tfc:wood/wood/ash')
  event.add('forge:sap_log', 'afc:wood/log/mahogany')
  event.add('forge:sap_log', 'afc:wood/wood/mahogany')
  event.add('forge:sap_log', 'afc:wood/log/teak')
  event.add('forge:sap_log', 'afc:wood/wood/teak')
  event.add('forge:sap_log', 'afc:wood/log/ipe')
  event.add('forge:sap_log', 'afc:wood/wood/ipe')
  event.add('forge:sap_log', 'tfc:wood/log/blackwood')
  event.add('forge:sap_log', 'tfc:wood/wood/blackwood')
  event.add('forge:sap_log', 'afc:wood/log/tualang')
  event.add('forge:sap_log', 'afc:wood/wood/tualang')
  
  
  event.add('forge:resin_log', 'afc:wood/log/cypress')
  event.add('forge:resin_log', 'afc:wood/wood/cypress')
  event.add('forge:resin_log', 'tfc:wood/log/pine')
  event.add('forge:resin_log', 'tfc:wood/wood/pine')
  event.add('forge:resin_log', 'afc:wood/log/redcedar')
  event.add('forge:resin_log', 'afc:wood/wood/redcedar')
  event.add('forge:resin_log', 'tfc:wood/log/spruce')
  event.add('forge:resin_log', 'tfc:wood/wood/spruce')
  event.add('forge:resin_log', 'tfc:wood/log/douglas_fir')
  event.add('forge:resin_log', 'tfc:wood/wood/douglas_fir')
  event.add('forge:resin_log', 'tfc:wood/log/white_cedar')
  event.add('forge:resin_log', 'tfc:wood/wood/white_cedar')
  
  event.add('forge:oak_resin_log', 'tfc:wood/log/oak')
  event.add('forge:oak_resin_log', 'tfc:wood/wood/oak')
  event.add('forge:oak_resin_log', 'afc:wood/log/black_oak')
  event.add('forge:oak_resin_log', 'afc:wood/wood/black_oak')
  
  event.add('forge:chestnut_resin_log', 'tfc:wood/log/chestnut')
  event.add('forge:chestnut_resin_log', 'tfc:wood/wood/chestnut')
  
  event.add('forge:fig_sap_log', 'afc:wood/log/fig')
  event.add('forge:fig_sap_log', 'afc:wood/wood/fig')
  
  event.add('forge:mangrove_sap_log', 'tfc:wood/log/mangrove')
  event.add('forge:mangrove_sap_log', 'tfc:wood/wood/mangrove')
  
  event.add('forge:maple_sap_log', 'tfc:wood/log/maple')
  event.add('forge:maple_sap_log', 'tfc:wood/wood/maple')
  
  event.add('forge:eucalyptus_gum_log', 'afc:wood/log/eucalyptus')
  event.add('forge:eucalyptus_gum_log', 'afc:wood/wood/eucalyptus')
  event.add('forge:eucalyptus_gum_log', 'afc:wood/log/rainbow_eucalyptus')
  event.add('forge:eucalyptus_gum_log', 'afc:wood/wood/rainbow_eucalyptus')
  
  event.add('forge:water_log', 'afc:wood/log/baobab')
  event.add('forge:water_log', 'afc:wood/wood/baobab')
  
  event.add('forge:willow_sap_log', 'tfc:wood/log/willow')
  event.add('forge:willow_sap_log', 'tfc:wood/wood/willow')
  event.add('forge:willow_sap_log', 'afc:wood/log/poplar')
  event.add('forge:willow_sap_log', 'afc:wood/wood/poplar')
  
  event.add('forge:birch_sap_log', 'tfc:wood/log/birch')
  event.add('forge:birch_sap_log', 'tfc:wood/wood/birch')
  event.add('forge:sycamore_sap_log', 'tfc:wood/log/sycamore')
  event.add('forge:sycamore_sap_log', 'tfc:wood/wood/sycamore')
  
  event.add('forge:palm_sap_log', 'tfc:wood/log/palm')
  event.add('forge:palm_sap_log', 'tfc:wood/wood/palm')
  
  event.add('forge:rosewood_sap_log', 'tfc:wood/log/rosewood')
  event.add('forge:rosewood_sap_log', 'tfc:wood/wood/rosewood')
  
  event.add('forge:ironwood_sap_log', 'afc:wood/log/ironwood')
  event.add('forge:ironwood_sap_log', 'afc:wood/wood/ironwood')
  
  event.add('forge:sequoia_sap_log', 'tfc:wood/log/sequoia')
  event.add('forge:sequoia_sap_log', 'tfc:wood/wood/sequoia')
  
  event.add('forge:gum_arabic_log', 'tfc:wood/log/acacia')
  event.add('forge:gum_arabic_log', 'tfc:wood/wood/acacia')
  event.add('forge:gum_arabic_log', 'afc:wood/log/gum_arabic')
  event.add('forge:gum_arabic_log', 'afc:wood/wood/gum_arabic')
  
  event.add('forge:eucalyptus_leaves', 'afc:wood/leaves/eucalyptus')
  event.add('forge:eucalyptus_leaves', 'afc:wood/leaves/rainbow_eucalyptus')
  
  event.add('forge:hickory_sap_log', 'tfc:wood/log/hickory')
  event.add('forge:hickory_sap_log', 'tfc:wood/wood/hickory')
  
  event.add('forge:gem_dust', 'gtceu:topaz_dust')
  event.add('forge:gem_dust', 'gtceu:blue_topaz_dust')
  event.add('forge:gem_dust', 'gtceu:amethyst_dust')
  event.add('forge:gem_dust', 'gtceu:diamond_dust')
  event.add('forge:gem_dust', 'gtceu:emerald_dust')
  event.add('forge:gem_dust', 'gtceu:lapis_dust')
  event.add('forge:gem_dust', 'gtceu:opal_dust')
  event.add('forge:gem_dust', 'gtceu:pyrite_dust')
  event.add('forge:gem_dust', 'gtceu:ruby_dust')
  event.add('forge:gem_dust', 'gtceu:sapphire_dust')
  event.add('forge:gem_dust', 'gtceu:green_sapphire_dust')
  
  event.add('forge:gem_dust', 'gtceu:sodalite_dust')
  event.add('forge:gem_dust', 'gtceu:lazurite_dust')
  event.add('forge:gem_dust', 'gtceu:pyrope_dust')
  event.add('forge:gem_dust', 'gtceu:almandine_dust')
  event.add('forge:gem_dust', 'gtceu:yellow_garnet_dust')
  event.add('forge:gem_dust', 'gtceu:red_garnet_dust')
  
  event.add('forge:gem_dust', 'gtceu:malachite_dust')
  event.add('forge:gem_dust', 'gtceu:realgar_dust')
  event.add('forge:gem_dust', 'gtceu:andradite_dust')
  event.add('forge:gem_dust', 'gtceu:cinnabar_dust')
  event.add('forge:gem_dust', 'gtceu:grossular_dust')
  event.add('forge:gem_dust', 'gtceu:rutile_dust')
  event.add('forge:gem_dust', 'gtceu:spessartine_dust')
  event.add('forge:gem_dust', 'gtceu:uvarovite_dust')
  
  event.add('forge:gem_dust', 'gtceu:olivine_dust')
  event.add('forge:gem_dust', 'gtceu:apatite_dust')
  event.add('forge:gem_dust', 'gtceu:monazite_dust')
  
  event.add('forge:sandpaper_paper_mat', 'tfc:unrefined_paper')
  event.add('forge:sandpaper_paper_mat', 'minecraft:paper')
  event.add('forge:sandpaper_paper_mat', 'tfc:burlap_cloth')
  event.add('forge:sandpaper_paper_mat', 'tfc:silk_cloth')
  event.add('forge:sandpaper_paper_mat', 'tfc:wool_cloth')
  event.add('tfc:knives', '#gtceu:tools/crafting_knives')
  
  event.add('forge:crafting_gem', 'gtceu:topaz_gem')
  event.add('forge:crafting_gem', 'gtceu:blue_topaz_gem')
  event.add('forge:crafting_gem', 'gtceu:amethyst_gem')
  event.add('forge:crafting_gem', 'gtceu:diamond_gem')
  event.add('forge:crafting_gem', 'gtceu:emerald_gem')
  event.add('forge:crafting_gem', 'gtceu:lapis_gem')
  event.add('forge:crafting_gem', 'gtceu:opal_gem')
  event.add('forge:crafting_gem', 'gtceu:pyrite_gem')
  event.add('forge:crafting_gem', 'gtceu:ruby_gem')
  event.add('forge:crafting_gem', 'gtceu:sapphire_gem')
  event.add('forge:crafting_gem', 'gtceu:green_sapphire_gem')
  
  event.add('forge:crafting_gem', 'gtceu:sodalite_gem')
  event.add('forge:crafting_gem', 'gtceu:lazurite_gem')
  event.add('forge:crafting_gem', 'gtceu:pyrope_gem')
  event.add('forge:crafting_gem', 'gtceu:almandine_gem')
  event.add('forge:crafting_gem', 'gtceu:yellow_garnet_gem')
  event.add('forge:crafting_gem', 'gtceu:red_garnet_gem')
  
  event.add('forge:crafting_gem', 'gtceu:malachite_gem')
  event.add('forge:crafting_gem', 'gtceu:realgar_gem')
  event.add('forge:crafting_gem', 'gtceu:andradite_gem')
  event.add('forge:crafting_gem', 'gtceu:cinnabar_gem')
  event.add('forge:crafting_gem', 'gtceu:grossular_gem')
  event.add('forge:crafting_gem', 'gtceu:rutile_gem')
  event.add('forge:crafting_gem', 'gtceu:spessartine_gem')
  event.add('forge:crafting_gem', 'gtceu:uvarovite_gem')
  
  event.add('forge:crafting_gem', 'gtceu:olivine_gem')
  event.add('forge:crafting_gem', 'gtceu:apatite_gem')
  event.add('forge:crafting_gem', 'gtceu:monazite_gem')
  
  event.add('tfc:hammers', '#gtceu:tools/crafting_hammers')
  
  event.add('minecraft:any_bronze_double_plate', 'gtceu:double_bronze_plate')
  event.add('minecraft:any_bronze_double_plate', 'gtceu:double_bismuth_bronze_plate')
  event.add('minecraft:any_bronze_double_plate', 'gtceu:double_black_bronze_plate')
  
  event.add('minecraft:any_bronze_plate', 'gtceu:bronze_plate')
  event.add('minecraft:any_bronze_plate', 'gtceu:bismuth_bronze_plate')
  event.add('minecraft:any_bronze_plate', 'gtceu:black_bronze_plate')
  
  event.add('tgs:any_glass_work_lime_dust', 'gtceu:lime_dust')
  event.add('tgs:any_glass_work_lime_dust', 'gtceu:quicklime_dust')
  event.add('tgs:any_glass_work_lime_dust', 'gtceu:calcium_hydroxide_dust')
  
  event.add('tgs:any_glass_work_potash_dust', 'gtceu:potash_dust')
  event.add('tgs:any_glass_work_potash_dust', 'gtceu:saltpeter_dust')
  event.add('tgs:any_glass_work_potash_dust', 'gtceu:soda_ash_dust')
  
  event.add('tgs:any_glass_work_quartz_sand_dust', 'gtceu:quartzite_dust')
  event.add('tgs:any_glass_work_quartz_sand_dust', 'gtceu:quartz_sand_dust')
}